### ISSUE TITLE
Garage Phone App

### ISSUE THREAD

**Issue by jordylolx** [tnj-development/inventory#8]
[      script:qb-core] SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:200: attempt to index a nil value (global 'Garages')
[      script:qb-core] > ref (@qb-phone/server/main.lua:200)
[      script:qb-core] > Query.onResult (@oxmysql/dist/build.js:21715)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:11918)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:78)
[      script:qb-core] 

how do i fix this

**Comment by jay-fivem** [comment]
Is this an inventory issue? No its ur phone, Thanks Jay
